[project]
name = "asteroids"
version = "0.1.0"
description = "boot.dev Asteroids project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "python-lsp-server>=1.12.2",
]
